[build]
pre-build = [
    # https://aws.github.io/aws-lc-rs/requirements/linux.html
    "apt-get update",
    "apt-get install --assume-yes libclang1 cargo",
    "cargo install --force --locked bindgen-cli",
]

[build.env]
passthrough = ["RUSTFLAGS"]

[target.x86_64-pc-windows-gnu]
pre-build = [
    # Install NASM for rustls, which deps on aws-lc-rs by default, and it needs NASM
    "apt-get update",
    "apt-get install --assume-yes libclang1 nasm cargo",
    "cargo install --force --locked bindgen-cli",
]

[target.aarch64-unknown-linux-gnu]
pre-build = []

[target.aarch64-unknown-linux-musl]
pre-build = []

[target.x86_64-unknown-linux-gnu]
pre-build = []

[target.x86_64-unknown-linux-musl]
pre-build = []

[target.i686-unknown-linux-gnu]
pre-build = []

[target.aarch64-apple-darwin]
pre-build = []

[target.x86_64-apple-darwin]
pre-build = []
